[ .exclude, 
."http://eol.org/schema/terms/statisticalMethod",
."http://purl.org/dc/terms/source",
."http://rs.tdwg.org/dwc/terms/lifeStage",
."http://rs.tdwg.org/dwc/terms/measurementID",
."http://rs.tdwg.org/dwc/terms/measurementRemarks",
."http://rs.tdwg.org/dwc/terms/measurementType",
."http://rs.tdwg.org/dwc/terms/measurementUnit",
."http://rs.tdwg.org/dwc/terms/measurementValue",
."http://rs.tdwg.org/dwc/terms/referenceID",
."http://rs.tdwg.org/dwc/terms/scientificName",
."http://rs.tdwg.org/dwc/terms/sex",
."http://rs.tdwg.org/dwc/terms/taxonID",
."infer",
."taxonID"] | @tsv
